export { CatalogIcon } from './CatalogIcon'
export { MenuIcon } from './MenuIcon'
export { SearchIcon } from './SearchIcon'
export { RatingIcon } from './RatingIcon'
export { FavoritesIcon } from './FavoritesIcon'
export { ProfileIcon } from './ProfileIcon'
