export enum Emoji {
  'motivation' = '🔥',
  'creativity' = '🧠',
  'support' = '⚡️',
  'members' = '📬',
  'completed' = '🏆',
  'abandoned' = '🕸',
  'followers' = '🥷',
  'following' = '⭐',
  'runningDays' = '⏳',
  'points' = '❤️',
  'nextLevelPoints' = '',
  'progress' = '',
  'level' = '',
}
