export enum Emoji {
  'motivation' = '🦾',
  'creativity' = '🧠',
  'support' = '⚡️',
  'members' = '📬',
  'completed' = '🏆',
  'abandoned' = '🕸',
  'followers' = '🥷',
  'following' = '⭐',
  'runningDays' = '⏳',
  'points' = '🦾',
  'nextLevelPoints' = '',
  'progress' = '',
  'level' = '',
  // notifications:
  'new-goal' = '💎',
  'new-follower' = '⭐',
  'added-points' = '🦾',
  'new-question' = '❓',
  'new-support' = '⚡️',
  'new-answer' = '📮',
  'new-feedback' = '💭',
  'web-coverage' = '🕸',
  'notification' = '🛎',
}
