export type Device =
  | 'desktop'
  | 'tablet'
  | 'smartphone'
  | 'feature phone'
  | 'phablet'
  | 'console'
  | 'tv'
  | 'car browser'
  | 'smart display'
  | 'camera'
  | 'portable media player'
  | 'smart speaker'
  | 'wearable'
  | 'peripheral'
